x <- read.table("test/X_test.txt")
y <- read.table("test/Y_test.txt")
sub<-read.table("test/subject_train.txt")
texy <- cbind(y,x)
texy<-cbind(texy,sub)
trx <- read.table("train/X_train.txt")
try <- read.table("train/Y_train.txt")
trsub <- read.table("train/subject_train.txt")
trxy <- cbind(try,trx)
trxy<-cbind(trxy,trsub)
mxy<-rbind(texy,trxy)
write.table(mxy,file="mergedata.txt",row.names=FALSE)
